config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get "create" => "pages#create"
  get "join" => "pages#join"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def create
  end
  def join
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<style>
li.left {float: left;}
</style>

<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Cruise My Trip", root_path, class: "navbar-brand" %>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Create", create_path %></li>
     
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Location">
        </div>
        <button type="submit" class="btn btn-default">Search for Outings</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="left"><%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
        
        <% else %>
          <li class="left"><%= link_to "Sign in", new_user_session_path %></li>
          <li class="left"><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>

        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_headercreate.html.erb
<style>
li.left {float: left;}
</style>

<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "Cruise My Trip", root_path, class: "navbar-brand" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Join", join_path %></li>
      </ul>

      
      <ul class="nav navbar-nav navbar-right">
        
        <% if user_signed_in? %>
          <li class="left"><%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
        
        <% else %>
          <li class="left"><%= link_to "Sign in", new_user_session_path %></li>
          <li class="left"><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>

        </li>
      </ul>
    </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_updates.html.erb

  <div class="jumbotron">
    <p id="bottom"> 
    Updates: <br>
    26-09-2016 ==> welcome page is ready, publishing soon. Stay tuned ! <br>
    29-09-2016 ==> Created page is ready with nav bar <br>
    04-10-2016 ==> app pushed to heroku <br>
    08-10-2016 ==> Now you can Sign in, Sign up and Logout. <br>

    </p>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cruisemytrip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>

<%= yield %>

</body>
</html>

app/views/pages/create.html.erb
<div >
	<style>
		.btn-lg {height: 200px; width: 400px; align-items: center; padding-top: 100px; padding-top: 100px}
		div.btn {text-align: center; padding: 100px}
		.jumbotron {width: 500px;}
	</style>
	<%= render 'layouts/headercreate' %>
	</div>
<div class="container">
	<center>
		<br><a href="#", class= "btn btn-primary btn-lg"> Tourism </a>
		<a href="#", class= "btn btn-primary btn-lg"> Attend an event </a>
		<a href="#", class= "btn btn-primary btn-lg"> Out of town adventure </a>
		<a href="#", class= "btn btn-primary btn-lg"> Local activity </a>
		<a href="#", class= "btn btn-primary btn-lg"> Multi-purpose </a>
		</center>
</div>
<center>
<br>
<br>
<div class="jumbotron">
<center>
	<form>
  <div class="form-group">
    <input type="location" class="form-control" id="origin" placeholder="Y Combinator">
  </div>
  <div class="form-group">
    <input type="date" class="form-control" id="date1">
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> I'm returning here
    </label>
  </div>
  <button type="submit" class="btn btn-default">Ready to go</button>
</form>
</center>
</div>
</center>

</div>

app/views/pages/home.html.erb
<div class="container">
	<style> 
		h1.top {font-size: 6em;}
		h3.sub {text-align: center;}
		div.create {float:left; padding-left: 50px; padding-top: 20px; padding-bottom: 20px}
		div.join {float:right; padding-right: 50px; padding-top: 20px; padding-bottom: 20px}
		h1.h {text-align: center; padding-top: 300px}
		div.how {align-items: center; padding-bottom: 100px}
		.btn-lg {height: 200px; width: 400px; text-align: center; vertical-align: center}
		h5.note {color: red; text-align: center;}
	</style>
	
	<h5 class="note">Note: As promised, i am learning to hack my own prototype. please <a href="#bottom">Click Here </a> to go to the UPDATES</h5>

	<center>		
		<h1 class="top">Welcome to Cruise My Trip</h1>
		<h3 class="sub">We connect you to those who can</h1>			
	</center>

	<div class="create">
		<%= link_to "Create", create_path, class: "btn btn-primary btn-lg" %>
	</div> 
	
	<div class="join">
		<%= link_to "Join", join_path, class: "btn btn-primary btn-lg" %>
	</div>
	
	<h1 class="h">How it Works</h1>
	
	<div class="how">
		<%= image_tag "howitworks.jpg" %>
	</div>
	

	<%= render 'layouts/updates' %>
	

</div>

app/views/pages/join.html.erb
<style>
	h1.slogan {color: red; font-weight: bold;}
</style>

<%= render 'layouts/header' %>
<div class="container"> 
	<center>
		<h1 class="slogan"> Connect To Those Who Can</h1>
	</center>
</div>